# Agent Configuration
ai:
  # Plugin can be "gemini" or "ollama"
  plugin: "gemini"
  
  gemini:
    api_key: "YOUR_KEY_HERE" # Can be set via GEMINI_API_KEY env var
    model: "gemini-2.5-pro"

  ollama:
    model: "qwen2.5:3b" # Can be set via OLLAMA_MODEL
    base_url: "http://localhost:11434"

  zai:
    model: "glm-4.5"

planner:
  timeout: 220 # Seconds

amadeus:
  limit:
    flight: 10
    hotel: 10
  timeout: 30 # Seconds
  cache_ttl:
    location: 240 # Hours
    flight: 240 # Hours
    hotel: 240 # Hours
  # client_id: "YOUR_ID" # Can be set via AMADEUS_CLIENT_ID
  # client_secret: "YOUR_SECRET" # Can be set via AMADEUS_CLIENT_SECRET

tavily:
  timeout: 30 # Seconds
  # api_key: "YOUR_KEY"

log:
  level: "debug"