# Agent Configuration
ai:
  # Plugin can be "gemini" or "ollama"
  plugin: "gemini"
  
  gemini:
    api_key: "YOUR_KEY_HERE" # Can be set via GEMINI_API_KEY env var
    model: "gemini-2.5-pro"

  ollama:
    model: "qwen2.5:3b" # Can be set via OLLAMA_MODEL
    base_url: "http://localhost:11434"

amadeus:
  # client_id: "YOUR_ID" # Can be set via AMADEUS_CLIENT_ID
  # client_secret: "YOUR_SECRET" # Can be set via AMADEUS_CLIENT_SECRET
